export const ROUTER = {
  LOGIN: "/login",
  MANAGER_MEMBER: "/manager-member",
  MANABER_MEMBER_DETAIL: "/manager-member/detail",
  MANABER_MEMBER_DETAIL_ORDER: "/manager-member/detail/order",
  MANABER_MEMBER_DETAIL_MATCHING: "/manager-member/detail/matching",
  MANABER_MEMBER_DETAIL_STORE_REVIEW: "/manager-member/detail/store-review",
  MANABER_MEMBER_DETAIL_MATCHING_REVIEW:
    "/manager-member/detail/matching-review",
  MANAGER_ADMIN: "/manager-admin",
  COMPANY: "/list-company",
  COMPANY_DETAIL: "/list-company/detail",
  COMPANY_DETAIL_EDIT: "/list-company/detail/edit",
  COMPANY_REGISTER: "/register-company",
  OPERATIONS_MATCHING: "/operations-matching",
  OPERATIONS_COMPANY_REVIEW: "/operations-company-review",
  OPERATIONS_MATCHING_REVIEW: "/operations-matching-review",
  OPERATIONS_ANNOUNCEMENT: "/operations-announcement",
  OPERATIONS_ANNOUNCEMENT_ADD: "/operations-announcement/add",
  OPERATIONS_EVENT: "/operations-event",
  OPERATIONS_EVENT_ADD: "/operations-event/add",
  OPERATIONS_EVENT_EDIT: "/operations-event/edit",
  OPERATIONS_EVENT_DETAIL: "/operations-event/detail",
  OPERATIONS_FAQ: "/operations-faq",
  ORDER: "/order",
  ORDER_DETAIL: "/order/detail",
  RESERVATION_TICKET: "/reservation-ticket",
  RESERVATION_MATCHING: "/reservation-matching",
  SYSTEM_COMPANY_CATEGORY: "/system-company-category",
  SYSTEM_WHO_CATEGORY: "/system-who-category",
  SYSTEM_WHERE_CATEGORY: "/system-where-category",
  SYSTEM_ENVIRONMENT_VARIABLE_SETTING: "/system-environment-variables-setting",
  SYSTEM_TERM_AND_CONDITION: "/system-term-and-condition",
  SYSTEM_BANNER_MANAGEMENT: "/system-banner-management",
  STORE_OWNER_ORDER: "/store-owner-order",
  STORE_OWNER_ORDER_DETAIL: "/store-owner-order/detail",
  STORE_OWNER_NOTICE: "/store-owner-notice",
  ALL: "*",
};
